### ISSUE TITLE
New Skill Suggestion: Enchantment effects

### ISSUE THREAD

**Issue by vayllonyx** [Xemorr/superheroes#12]
This might be a lot harder to code, but giving enchantment effects to players without gear (ideally admins could toggle what gear it works with/requires) would really open up builds, and improve upon already existing ones. 

For instance, adding something like the following to the Enderman hero would really round out the Enderman:

skill: ENCHANTED
   type: SILK_TOUCH
   gearType: HAND 
   
For Dolphin it might look something like:

skill: ENCHANTED
  type: AQUA_AFFINITY
  gearType: 

Leaving gearType blank on Dolphin means it works with all tools and armor, or without any, whereas gearType: HAND or whatever would mean Enderman could only silk touch up things with an empty hand unless they had another enchanted item. 

Idk i’m not a coder lol, just thought it could be cool.

**Comment by Xemorr** [comment]
As far as I know, you can't give literal enchantment effects to players without it going on an item, things like silk touch could be emulated, but I don't think effects like aqua affinity can be as they're mostly client-side. How about an enchantment skill that guarantees a certain enchant on your item when you go to enchant? That could be interesting.

**Comment by vayllonyx** [comment]
Yeah that could be cool. Very different flavor, but cool.

I’ve actually figured out how to get the effects I wanted on Enderman (using Convert Drops on dirt blocks) and Dolphin (using potion type Conduit_Power) anyway, lol.

Just so you know, i’m basically trying to use your plugin to mimic the Origins mod by Apace100 (link: https://www.curseforge.com/minecraft/mc-mods/origins ) purely server side so it works with vanilla clients.

Other skill/hero ideas that come from that mod would be climbing, place an object when attacking (both from Arachnid), a skill that applies diet limitations (though Consume could be used similarly), and various skills that apply negative effects like burning in daylight, drowning in air, or taking damage from water.
