### ISSUE TITLE
New superpower suggestion: Origin

### ISSUE THREAD

**Issue by ItsHydra0** [Xemorr/superheroes#14]
When choosed, you get a wooden sword with an enchant named **Origin** which allows you to get spawn eggs of mobs you kill with that sword instead of the loot. Downside is that its only a wooden sword and without Unbreaking and Mending, it can easily be broken so you have to be careful about that. If you are killed, you don't drop the sword and have it in your inventory when respawned. Since you do not get the loot, it's just for transporting mobs which is not too overpowered.

**Comment by Xemorr** [comment]
I'm not sure if this would fit as a superpower due to the limited usability of it, if your sword breaks you're back to a normal pleb. I do like the idea though, some kind of system where when you kill a mob as a certain hero it turns back into a spawn egg is intriguing.

**Comment by ItsHydra0** [comment]
Oh, then what about giving the sword Unbreakable tag

**Comment by Xemorr** [comment]
Yeah that'd work

**Comment by Xemorr** [comment]
You can do this with SuperheroesPlusUltra
