### ISSUE TITLE
Plugin automatically gives players a power despite setting poweronstart to false.

### ISSUE THREAD

**Issue by TuckerAndrews3** [Xemorr/superheroes#20]
What minecraft version did it occur on?
1.16.5
What superheroes version did it occur on?
2.0.6
Please post the relevant log to pastebin (if there is one)
No error
Description of the issue:
The plugin automatically gives players a superpower despite me setting poweronstart to false. I want my players to have to get the item listed in the config to give them their powers instead of them just being assigned one when they first join.

**Comment by Xemorr** [comment]
This is solved in 2.1.0.
