### ISSUE TITLE
Request for adding new features.

### ISSUE THREAD

**Issue by 3nB3n** [Xemorr/superheroes#22]
I think that adding a feature in which allows effects to be given to players when they hold a certain item would make the plugin more customizable. Also, I'd like to get a feature were lava or water give effects. This could really balance some OP heros.

**Comment by 3nB3n** [comment]
Its been 19 days ;-; You guys told me to put all the issues here and after almost 20 days I get no response.

**Comment by Xemorr** [comment]
This feature is not coming to Superheroes2 and is outside the scope of this project, it is being added to the addon SuperheroesPlusUltra.
