### ISSUE TITLE
[Suggestion] A hero selection GUI

### ISSUE THREAD

**Issue by BookWyrm114** [Xemorr/superheroes#26]
Hello, I would like to suggest a small feature, it would be nice if there were a GUI for players to select a hero, the heroes could be displayed with player-heads or items with short descriptions in the lore, these items and lore could be defined in the hero's YML file. that way, upon going the server, or some other event, server owners could show the GUI to players to allow them to select a hero.

**Comment by Xemorr** [comment]
Hi, this is a pretty good idea. The reason it isn't here currently is /hero select and similar commands were meant to be for admins but it just turns out most servers don't use it like that. I'll consider it.

**Comment by BookWyrm114** [comment]
My idea is that it could be a command to show the GUI, so that players can use it without permissions, but the GUI would have to be triggered by an admin or console command. Also it could still be used by servers which don’t want to use it that way as a slightly easier alternative to selecting a hero, as well as an easy way to view what each hero does by using item lore. Thank you, and even if the feature is not implemented, keep up the good work on the plugin, this has to be one of the best plugins I’ve ever seen, and it’s incredibly useful and fun to play around with different powers and see how they can all be used.

**Comment by Xemorr** [comment]
This is completed now
