### ISSUE TITLE
[QUESTION] What is dracula's power?

### ISSUE THREAD

**Issue by sctgits** [Xemorr/superheroes#33]
I can't seem to find the use of dracula. I tried sneak right click, sneak left click, normal left and right click. Yet none does any

**Comment by Xemorr** [comment]
It is a low percentage lifesteal on every attack. Try being on low health and getting a critical hit on a Pig say. Make sure the regeneration can't be confused with your hunger.

**Comment by sctgits** [comment]
> It is a low percentage lifesteal on every attack. Try being on low health and getting a critical hit on a Pig say. Make sure the regeneration can't be confused with your hunger.

I see. Also, can you add a command where people can check what superpower they have?
