### ISSUE TITLE
[Suggestion] Update information

### ISSUE THREAD

**Issue by ClamorBits** [Xemorr/superheroes#34]
Either both Spigot page and official Wiki didn't have complete information. The Wiki should have demonstration GIF of all of the powers.

Also, all survival server tips video seems to be invalid. I would like to help you update the informations, if you'd like to. But people really need full information about the plugin.

**Comment by Xemorr** [comment]
Hi, the video was released in Superheroes v1 and is mostly just a demonstration of powers which is for the most part still up to date. The main part which isn't is the /power command as that is now /hero. I am happy to work with you if you want to write pages for the wiki etc

Join the discord and talk to me on there if you're interested in that.

**Comment by ClamorBits** [comment]
> Hi, the video was released in Superheroes v1 and is mostly just a demonstration of powers which is for the most part still up to date. The main part which isn't is the /power command as that is now /hero. I am happy to work with you if you want to write pages for the wiki etc
> 
> Join the discord and talk to me on there if you're interested in that.

Hey Xemorr. Sadly my parents don't allow me to use Discord for personal reason. Can you contact me on contactpausenimations@gmail.com instead? Thanks

**Comment by ClamorBits** [comment]
Hey @Xemorr. Sadly I cannot use Discord for personal reason. Can you contact me at ClamorBits@gmail.com instead? Thanks
