### ISSUE TITLE
What was the use of import and export command?

### ISSUE THREAD

**Issue by ClamorBits** [Xemorr/superheroes#37]
There is a command named `/hero import` and `/hero export`. I can't seem to find a help with that. I'm going to make a YouTube video showcasing your plugin. So I also need to know all my commands. If the video finished I'll reach to you so you can put it on the Spigot page.

**Comment by Xemorr** [comment]
Hi Clamor, /hero import and /hero export are used for switching between storage types. You use /hero export and it dumps the content of the current database being used into a file, and then you change the storage type you're using, reload, and then /hero import to restore the data.

**Comment by ClamorBits** [comment]
Alright, thanks @Xemorr
