### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by EquableProgram69** [Xemorr/superheroes#41]
What version of minecraft is the most recent superheros plugin for?

I can't seem to find this seemingly vital information.

**Comment by Xemorr** [comment]
1.19
![image](https://user-images.githubusercontent.com/31805746/185755118-5761b004-a931-4337-93c7-f9bffd744d5d.png)

You can generally get away with most recent versions of minecraft though as I'm not doing anything particularly funky
