### ISSUE TITLE
Saturation Bug? not sure if intended

### ISSUE THREAD

**Issue by shock2oo3** [Xemorr/superheroes#42]
What minecraft version did it occur on? 1.19.2
What superheroes version did it occur on? 3.0.4
Description of the issue: with full hunger, you can keep eating consumables and gaining saturation (eg: eat a stack of ink). even taking damage, saturation gets so high you can't eat normal food and will gain health very slowly for a long time. try switching to doomfist with crazy saturation from a consumable lol. maybe reset hunger after a certain saturation level?

**Comment by Xemorr** [comment]
Dear shock2oo3, 

I can see that this issue can happen, I will work to solve it for the next update

**Comment by Xemorr** [comment]
Solved in 3.1.0
