### ISSUE TITLE
an ability with mobs

### ISSUE THREAD

**Issue by adhamat** [Xemorr/superheroes#8]
What minecraft version did it occur on?
What superheroes version did it occur on?
Please post the relevant log to pastebin (if there is one)
Description of the issue:
each mob you tame or ride (dogs /cats/mule/horse) gives you an extra heart/2 healthpoints and it stays with you (cant go beyond 10 extra hearts/20health points)
for each none hostile mob you kill you lose a heart (cant go under 5 hearts/10 health points)

**Comment by Xemorr** [comment]
Hi, I don't think this skill fits within my plugin as it isn't interesting enough.
